name: Test and Prettify

on:
    pull_request:
        branches:
            - master

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "lts/*"

            - name: Install dependencies
              run: npm install --prefix api

            - name: Init MongoDB
              uses: supercharge/mongodb-github-action@1.11.0

            - name: Run tests
              run: npm run test:ci --prefix api
              env:
                  DATABASE_URL: mongodb://localhost:27017/ci
    prettify:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "lts/*"

            - name: Install dependencies
              run: npm install --prefix api

            - name: Run Prettier
              run: npm run prettier --prefix api

            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: "prettier: Apply formatting changes"
                  branch: ${{ github.head_ref }}
